WITH ABERTO AS (
    SELECT
        CR.IDEMPRESA,
        E.NOMEFANTASIA AS NOME_EMPRESA,
        CR.VALTITULO - COALESCE(CR.SUMVALPAGAMENTOTITULO, 0) AS VALOR
    FROM DBA.CONTAS_RECEBER CR
    INNER JOIN DBA.EMPRESA E
        ON E.IDEMPRESA = CR.IDEMPRESA
    WHERE CR.IDEMPRESA IN ({{FILIAIS}})
      AND CR.FLAGBAIXADA = 'F'
)
SELECT
    IDEMPRESA,
    NOME_EMPRESA,
    CAST(SUM(VALOR) AS NUMERIC(15,6)) AS VALOR_RECEBER_ABERTO
FROM ABERTO
GROUP BY IDEMPRESA, NOME_EMPRESA

UNION ALL

SELECT
    100 AS IDEMPRESA,
    'Todas as filiais' AS NOME_EMPRESA,
    CAST(SUM(VALOR) AS NUMERIC(15,6)) AS VALOR_RECEBER_ABERTO
FROM ABERTO

ORDER BY IDEMPRESA;
