WITH ABERTO AS (
    SELECT
        CP.IDEMPRESA,
        E.NOMEFANTASIA AS NOME_EMPRESA,
        CP.VALTITULO - COALESCE(CP.SUMVALPAGAMENTOTITULO, 0) AS VALOR
    FROM DBA.CONTAS_PAGAR CP
    INNER JOIN DBA.EMPRESA E
        ON E.IDEMPRESA = CP.IDEMPRESA
    WHERE CP.IDEMPRESA IN ({{FILIAIS}})
      AND CP.FLAGBAIXADA = 'F'
)
SELECT
    IDEMPRESA,
    NOME_EMPRESA,
    CAST(SUM(VALOR) AS NUMERIC(15,6)) AS VALOR_PAGAR_ABERTO
FROM ABERTO
GROUP BY IDEMPRESA, NOME_EMPRESA

UNION ALL

SELECT
    100 AS IDEMPRESA,
    'Todas as filiais' AS NOME_EMPRESA,
    CAST(SUM(VALOR) AS NUMERIC(15,6)) AS VALOR_PAGAR_ABERTO
FROM ABERTO

ORDER BY IDEMPRESA;
