SELECT
    ESTOQUE.DTMOVIMENTO AS DATA,
    ESTOQUE.IDEMPRESA,
    ESTOQUE.NOME AS NOME_EMPRESA,
    CAST(SUM(ESTOQUE.VENDABRUTA) AS NUMERIC(15,6)) AS VALOR_VENDA_BRUTA
FROM (
    SELECT
        DBA.ESTOQUE_ANALITICO.DTMOVIMENTO,
        CASE
            WHEN DBA.ESTOQUE_ANALITICO.IDVENDEDOR IN (3529,3490,3491,3530,8904) THEN 99
            ELSE DBA.EMPRESA.IDEMPRESA
        END AS IDEMPRESA,
        CASE
            WHEN DBA.ESTOQUE_ANALITICO.IDVENDEDOR IN (3529,3490,3491,3530,8904) THEN 'E-COMMERCE'
            ELSE DBA.EMPRESA.NOMEFANTASIA
        END AS NOME,
        CASE
            WHEN COALESCE(DBA.ESTOQUE_ANALITICO.NUMSEQUENCIAKIT,0) <= 0 AND DBA.OPERACAO_INTERNA.TIPOMOVIMENTO <> 'E'
            THEN DBA.ESTOQUE_ANALITICO.VALTOTLIQUIDO
            ELSE 0
        END AS VENDABRUTA
    FROM
        DBA.ESTOQUE_ANALITICO
        INNER JOIN DBA.NOTAS_ENTRADA_SAIDA
            ON DBA.NOTAS_ENTRADA_SAIDA.IDEMPRESA = DBA.ESTOQUE_ANALITICO.IDEMPRESA
            AND DBA.NOTAS_ENTRADA_SAIDA.IDPLANILHA = DBA.ESTOQUE_ANALITICO.IDPLANILHA
            AND DBA.NOTAS_ENTRADA_SAIDA.DTMOVIMENTO = DBA.ESTOQUE_ANALITICO.DTMOVIMENTO
        INNER JOIN DBA.NOTAS
            ON DBA.NOTAS.IDEMPRESA = DBA.ESTOQUE_ANALITICO.IDEMPRESA
            AND DBA.NOTAS.IDPLANILHA = DBA.ESTOQUE_ANALITICO.IDPLANILHA
            AND DBA.NOTAS.FLAGNOTACANCEL = 'F'
        INNER JOIN DBA.OPERACAO_INTERNA
            ON DBA.OPERACAO_INTERNA.IDOPERACAO = DBA.ESTOQUE_ANALITICO.IDOPERACAO
            AND DBA.OPERACAO_INTERNA.FLAGMOVPRODUTOS = 'T'
            AND DBA.OPERACAO_INTERNA.TIPOMOVIMENTO IN ('V','E')
        INNER JOIN DBA.EMPRESA
            ON DBA.EMPRESA.IDEMPRESA = DBA.ESTOQUE_ANALITICO.IDEMPRESA
    WHERE
        DBA.ESTOQUE_ANALITICO.IDOPERACAO <> 1301
        AND DBA.ESTOQUE_ANALITICO.IDEMPRESA IN ({{FILIAIS}})
        AND DBA.NOTAS_ENTRADA_SAIDA.TIPOITEMCATEGORIA NOT IN ('D8')
        AND DBA.ESTOQUE_ANALITICO.DTMOVIMENTO BETWEEN ? AND ?
) AS ESTOQUE
GROUP BY
    ESTOQUE.DTMOVIMENTO,
    ESTOQUE.IDEMPRESA,
    ESTOQUE.NOME
ORDER BY
    ESTOQUE.DTMOVIMENTO,
    ESTOQUE.IDEMPRESA;
