SELECT
    NES.DTMOVIMENTO AS DATA,
    NES.IDEMPRESA,
    E.NOMEFANTASIA AS NOME_EMPRESA,
    CAST(SUM(NES.VALCONTABIL) AS NUMERIC(15,6)) AS VALOR_CANCELAMENTOS
FROM DBA.NOTAS_ENTRADA_SAIDA NES
INNER JOIN DBA.NOTAS N
    ON NES.IDPLANILHA = N.IDPLANILHA
INNER JOIN DBA.USUARIO U
    ON U.IDUSUARIO = N.IDUSUARIO
INNER JOIN DBA.EMPRESA E
    ON E.IDEMPRESA = NES.IDEMPRESA
WHERE NES.DTMOVIMENTO BETWEEN ? AND ?
    AND NES.IDEMPRESA IN ({{FILIAIS}})
    AND N.FLAGNOTACANCEL = 'T'
GROUP BY
    NES.DTMOVIMENTO,
    NES.IDEMPRESA,
    E.NOMEFANTASIA
ORDER BY
    NES.DTMOVIMENTO,
    NES.IDEMPRESA;
