SELECT
    ESTOQUE.DTMOVIMENTO AS DATA,
    ESTOQUE.IDEMPRESA,
    ESTOQUE.NOME AS NOME_EMPRESA,
    CAST(SUM(ESTOQUE.LUCRO) AS NUMERIC(15,6)) AS LUCRO_LIQUIDO
FROM (
    SELECT
        EA.DTMOVIMENTO,
        CASE
            WHEN EA.IDVENDEDOR IN (3529,3490,3491,3530,8904) THEN 99
            ELSE E.IDEMPRESA
        END AS IDEMPRESA,
        CASE
            WHEN EA.IDVENDEDOR IN (3529,3490,3491,3530,8904) THEN 'E-COMMERCE'
            ELSE E.NOMEFANTASIA
        END AS NOME,
        SUM(
            CASE
                WHEN EA.TIPOBAIXAMESTRE = 'K' THEN
                    (SELECT
                        CASE WHEN OI.TIPOMOVIMENTO = 'E' THEN -1 ELSE 1 END *
                        SUM(COALESCE(EST.VALLUCRO,0) * EST.QTDPRODUTO)
                     FROM DBA.ESTOQUE_ANALITICO EST
                     WHERE COALESCE(EST.NUMSEQUENCIAKIT,0) = EA.NUMSEQUENCIA
                       AND EST.IDPLANILHA = EA.IDPLANILHA
                       AND EST.IDSUBPRODUTO IN (
                           SELECT PK.IDSUBPRODUTO
                           FROM DBA.PRODUTO_KIT PK
                           WHERE PK.IDPRODUTOKIT = EA.IDPRODUTO
                             AND PK.IDSUBPRODUTOKIT = EA.IDSUBPRODUTO
                       )
                    )
                ELSE
                    CASE OI.TIPOMOVIMENTO
                        WHEN 'E' THEN -1 * COALESCE(EA.VALLUCRO,0) * EA.QTDPRODUTO
                        ELSE COALESCE(EA.VALLUCRO,0) * EA.QTDPRODUTO
                    END
            END
        ) AS LUCRO
    FROM
        DBA.ESTOQUE_ANALITICO EA
        INNER JOIN DBA.NOTAS_ENTRADA_SAIDA NES
            ON NES.IDEMPRESA = EA.IDEMPRESA
            AND NES.IDPLANILHA = EA.IDPLANILHA
            AND NES.DTMOVIMENTO = EA.DTMOVIMENTO
        INNER JOIN DBA.NOTAS N
            ON N.IDEMPRESA = EA.IDEMPRESA
            AND N.IDPLANILHA = EA.IDPLANILHA
            AND N.FLAGNOTACANCEL = 'F'
        INNER JOIN DBA.OPERACAO_INTERNA OI
            ON OI.IDOPERACAO = EA.IDOPERACAO
            AND OI.FLAGMOVPRODUTOS = 'T'
            AND OI.TIPOMOVIMENTO IN ('V','E')
        INNER JOIN DBA.EMPRESA E
            ON E.IDEMPRESA = EA.IDEMPRESA
    WHERE
        EA.IDOPERACAO <> 1301
        AND EA.IDEMPRESA IN ({{FILIAIS}})
        AND NES.TIPOITEMCATEGORIA NOT IN ('D8')
        AND EA.DTMOVIMENTO BETWEEN ? AND ?
    GROUP BY
        EA.DTMOVIMENTO,
        CASE WHEN EA.IDVENDEDOR IN (3529,3490,3491,3530,8904) THEN 99 ELSE E.IDEMPRESA END,
        CASE WHEN EA.IDVENDEDOR IN (3529,3490,3491,3530,8904) THEN 'E-COMMERCE' ELSE E.NOMEFANTASIA END,
        EA.TIPOBAIXAMESTRE,
        EA.NUMSEQUENCIA,
        EA.IDPLANILHA,
        EA.IDSUBPRODUTO,
        EA.IDPRODUTO,
        OI.TIPOMOVIMENTO
) AS ESTOQUE
GROUP BY
    ESTOQUE.DTMOVIMENTO,
    ESTOQUE.IDEMPRESA,
    ESTOQUE.NOME
ORDER BY
    ESTOQUE.DTMOVIMENTO,
    ESTOQUE.IDEMPRESA;
